on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a new GitHub Discussion
        id: create-discussion
        uses: abirismyname/create-discussion@v1.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          title: Feelings
          body: |
            Let's talk!
          repository-id: 388144015
          category-id: DIC_kwDOFyKbj84CRMSy
      - name: Print discussion url and id
        run: |
          echo discussion-id: ${{steps.create-discussion.outputs.discussion-id}} 
          echo discussion-url: ${{steps.create-discussion.outputs.discussion-url}}     
          
