# This is a basic workflow to help you get started with Actions

name: mikhail

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  fmt:
    name: format job
    runs-on: ubuntu-latest
    steps:
       - name: yada
         run: echo "::error file=./.yamllint.yaml,line=31,col=1::[empty-lines] too many blank lines (1 > 0)"
        
  
